import Skill from '../interfaces/Skills';

type FoundrySkillAttribute = 'for' | 'des' | 'con' | 'int' | 'sab' | 'car';

export interface FoundryCharSkill {
  value: number;
  atributo: FoundrySkillAttribute;
  outros: number;
  st: boolean;
  treinado: boolean;
  pda: boolean;
  treino: number;
  notes: string;
  mod: number;
  temp: number;
  bonus: number;
  penalidade: number;
  mais?: {
    [key: string]: {
      treinado: number;
      treino: number;
      atributo: FoundryCharSkill;
      outros: number;
    };
  };
}

export interface FoundryItem {
  name: string;
  type: string;
  flags: {
    core: {
      sourceId: string;
    };
  };
}

export const FOUNDRY_SKILLS = {
  [Skill.ACROBACIA]: 'acr',
  [Skill.ADESTRAMENTO]: 'ade',
  [Skill.ATLETISMO]: 'atl',
  [Skill.ATUACAO]: 'atu',
  [Skill.CAVALGAR]: 'cav',
  [Skill.CONHECIMENTO]: 'con',
  [Skill.CURA]: 'cur',
  [Skill.DIPLOMACIA]: 'dip',
  [Skill.ENGANACAO]: 'eng',
  [Skill.FORTITUDE]: 'for',
  [Skill.FURTIVIDADE]: 'fur',
  [Skill.GUERRA]: 'gue',
  [Skill.INICIATIVA]: 'ini',
  [Skill.INTIMIDACAO]: 'int',
  [Skill.INTUICAO]: 'intu',
  [Skill.INVESTIGACAO]: 'inv',
  [Skill.JOGATINA]: 'jog',
  [Skill.OFICIO]: 'ofi',
  [Skill.OFICIO_ALFAIATE]: 'ofi',
  [Skill.OFICIO_ALQUIMIA]: 'ofi',
  [Skill.OFICIO_ALVENARIA]: 'ofi',
  [Skill.OFICIO_ARMEIRO]: 'ofi',
  [Skill.OFICIO_ARTESANATO]: 'ofi',
  [Skill.OFICIO_CARPINTEIRO]: 'ofi',
  [Skill.OFICIO_CULINARIA]: 'ofi',
  [Skill.OFICIO_EGENHOQUEIRO]: 'ofi',
  [Skill.OFICIO_ESCRITA]: 'ofi',
  [Skill.OFICIO_ESCULTOR]: 'ofi',
  [Skill.OFICIO_ESTALAJADEIRO]: 'ofi',
  [Skill.OFICIO_FAZENDEIRO]: 'ofi',
  [Skill.OFICIO_JOALHEIRO]: 'ofi',
  [Skill.OFICIO_PINTOR]: 'ofi',
  [Skill.OFICIO_PESCADOR]: 'ofi',
  [Skill.OFICIO_MINERADOR]: 'ofi',
  [Skill.LADINAGEM]: 'lad',
  [Skill.LUTA]: 'lut',
  [Skill.MISTICISMO]: 'mis',
  [Skill.NOBREZA]: 'nob',
  [Skill.PERCEPCAO]: 'per',
  [Skill.PILOTAGEM]: 'pil',
  [Skill.PONTARIA]: 'pon',
  [Skill.REFLEXOS]: 'ref',
  [Skill.RELIGIAO]: 'rel',
  [Skill.SOBREVIVENCIA]: 'sob',
  [Skill.VONTADE]: 'von',
};

export const DEFAULT_SKILLS: Record<string, FoundryCharSkill> = {
  acr: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: true,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  ade: {
    value: 0,
    atributo: 'car',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  atl: {
    value: 0,
    atributo: 'for',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  atu: {
    value: 0,
    atributo: 'car',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  cav: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  con: {
    value: 0,
    atributo: 'int',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  cur: {
    value: 0,
    atributo: 'sab',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  dip: {
    value: 0,
    atributo: 'car',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  eng: {
    value: 0,
    atributo: 'car',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  for: {
    value: 0,
    atributo: 'con',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  fur: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: true,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  gue: {
    value: 0,
    atributo: 'int',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  ini: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  int: {
    value: 0,
    atributo: 'car',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  intu: {
    value: 0,
    atributo: 'sab',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  inv: {
    value: 0,
    atributo: 'int',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  jog: {
    value: 0,
    atributo: 'car',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  lad: {
    value: 0,
    atributo: 'des',
    st: true,
    pda: true,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  lut: {
    value: 0,
    atributo: 'for',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  mis: {
    value: 0,
    atributo: 'int',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  nob: {
    value: 0,
    atributo: 'int',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  ofi: {
    value: 0,
    atributo: 'int',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  per: {
    value: 0,
    atributo: 'sab',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  pil: {
    value: 0,
    atributo: 'des',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  pon: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  ref: {
    value: 0,
    atributo: 'des',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  rel: {
    value: 0,
    atributo: 'sab',
    st: true,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  sob: {
    value: 0,
    atributo: 'sab',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
  von: {
    value: 0,
    atributo: 'sab',
    st: false,
    pda: false,
    treinado: false,
    treino: 0,
    outros: 0,
    notes: '',
    mod: 0,
    temp: 0,
    bonus: 0,
    penalidade: 0,
  },
};
