/* eslint-disable @typescript-eslint/no-explicit-any */
import Skill from '../interfaces/Skills';

type FoundrySkillAttribute = 'for' | 'des' | 'con' | 'int' | 'sab' | 'car';

export interface FoundryCharSkill {
  value: number;
  atributo: FoundrySkillAttribute;
  outros: number;
  treinado: boolean;
  st: boolean;
  pda: boolean;
  size: boolean;
  condi: number;
  bonus: any[];
  custom: boolean;
  label: string;
  nome: string;
  mais?: {
    [key: string]: {
      treinado: number;
      treino: number;
      atributo: FoundrySkillAttribute;
      outros: number;
    };
  };
}

export interface FoundryItem {
  name: string;
  type: string;
  flags: {
    core: {
      sourceId: string;
    };
  };
}

export const FOUNDRY_SKILLS = {
  [Skill.ACROBACIA]: 'acro',
  [Skill.ADESTRAMENTO]: 'ades',
  [Skill.ATLETISMO]: 'atle',
  [Skill.ATUACAO]: 'atua',
  [Skill.CAVALGAR]: 'cava',
  [Skill.CONHECIMENTO]: 'conh',
  [Skill.CURA]: 'cura',
  [Skill.DIPLOMACIA]: 'dipl',
  [Skill.ENGANACAO]: 'enga',
  [Skill.FORTITUDE]: 'fort',
  [Skill.FURTIVIDADE]: 'furt',
  [Skill.GUERRA]: 'guer',
  [Skill.INICIATIVA]: 'inic',
  [Skill.INTIMIDACAO]: 'inti',
  [Skill.INTUICAO]: 'intu',
  [Skill.INVESTIGACAO]: 'inve',
  [Skill.JOGATINA]: 'joga',
  [Skill.OFICIO]: 'ofic',
  [Skill.OFICIO_ALFAIATE]: 'ofic',
  [Skill.OFICIO_ALQUIMIA]: 'ofic',
  [Skill.OFICIO_ALVENARIA]: 'ofic',
  [Skill.OFICIO_ARMEIRO]: 'ofic',
  [Skill.OFICIO_ARTESANATO]: 'ofic',
  [Skill.OFICIO_CARPINTEIRO]: 'ofic',
  [Skill.OFICIO_CULINARIA]: 'ofic',
  [Skill.OFICIO_EGENHOQUEIRO]: 'ofic',
  [Skill.OFICIO_ESCRITA]: 'ofic',
  [Skill.OFICIO_ESCULTOR]: 'ofic',
  [Skill.OFICIO_ESTALAJADEIRO]: 'ofic',
  [Skill.OFICIO_FAZENDEIRO]: 'ofic',
  [Skill.OFICIO_JOALHEIRO]: 'ofic',
  [Skill.OFICIO_PINTOR]: 'ofic',
  [Skill.OFICIO_PESCADOR]: 'ofic',
  [Skill.OFICIO_MINERADOR]: 'ofic',
  [Skill.LADINAGEM]: 'ladi',
  [Skill.LUTA]: 'luta',
  [Skill.MISTICISMO]: 'mist',
  [Skill.NOBREZA]: 'nobr',
  [Skill.PERCEPCAO]: 'perc',
  [Skill.PILOTAGEM]: 'pilo',
  [Skill.PONTARIA]: 'pont',
  [Skill.REFLEXOS]: 'refl',
  [Skill.RELIGIAO]: 'reli',
  [Skill.SOBREVIVENCIA]: 'sobr',
  [Skill.VONTADE]: 'vont',
};

export const DEFAULT_SKILLS: Record<string, FoundryCharSkill> = {
  acro: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: true,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  ades: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  atle: {
    value: 0,
    atributo: 'for',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  atua: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  cava: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  conh: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  cura: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  dipl: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  enga: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  fort: {
    value: 0,
    atributo: 'con',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  furt: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: true,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  guer: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  inic: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  inti: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  intu: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  inve: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  joga: {
    value: 0,
    atributo: 'car',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  ladi: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: true,
    pda: true,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  luta: {
    value: 0,
    atributo: 'for',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  mist: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  nobr: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  ofic: {
    value: 0,
    atributo: 'int',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  perc: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  pilo: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  pont: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  refl: {
    value: 0,
    atributo: 'des',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  reli: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: true,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  sobr: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
  vont: {
    value: 0,
    atributo: 'sab',
    outros: 0,
    treinado: false,
    st: false,
    pda: false,
    size: false,
    condi: 0,
    bonus: [],
    custom: false,
    label: '',
    nome: '',
  },
};
