import { Spell } from '../../interfaces/Spells';

export const spellsCircle1: Record<string, Spell> = {
  abencoarAlimentos: {
    nome: 'Abençoar Alimentos',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Alimento para 1 criatura',
    duracao: 'Cena',
  },
  acalmarAnimal: {
    nome: 'Acalmar Animal',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 animal',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  adagaMental: {
    nome: 'Adaga Mental',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 criatura',
    duracao: 'Instantânea',
    resistencia: 'Vontade parcial',
  },
  alarme: {
    nome: 'Alarme',
    execucao: 'Padrão',
    alcance: 'Curto',
    area: 'Esfera de 9m de raio',
    duracao: '1 dia',
  },
  amedrontar: {
    nome: 'Amedrontar',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 animal ou humanoide de ND 2 ou menor',
    duracao: 'Cena',
    resistencia: 'Vontade parcial',
  },
  areaEscorregadia: {
    nome: 'Área Escorregadia',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Quadrado de 3m ou 1 objeto',
    duracao: 'Cena',
    resistencia: 'Reflexos',
  },
  armaEspiritual: {
    nome: 'Arma Espiritual',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: 'Cena',
  },
  armaMagica: {
    nome: 'Arma Mágica',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 arma',
    duracao: 'Cena',
  },
  armaduraArcana: {
    nome: 'Armadura Arcana',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: 'Cena',
  },
  armamentoDaNatureza: {
    nome: 'Armamento da Natureza',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 arma',
    duracao: 'Cena',
  },
  aviso: {
    nome: 'Aviso',
    execucao: 'Movimento',
    alcance: 'Longo',
    alvo: '1 criatura',
    duracao: 'Instantânea',
  },
  bencao: {
    nome: 'Bênção',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Criaturas escolhidas',
    duracao: 'Cena',
  },
  caminhosDaNatureza: {
    nome: 'Caminhos da Natureza',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 arma',
    duracao: 'Cena',
  },
  comando: {
    nome: 'Comando',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 humanoide',
    duracao: '1 rodada',
    resistencia: 'Vontade anula',
  },
  compreensao: {
    nome: 'Compreensão',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura ou texto',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  concentracaoDeCombate: {
    nome: 'Concentração de Combate',
    execucao: 'Livre',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: '1 rodada',
  },
  conjurarMonstro: {
    nome: 'Conjurar Monstro',
    execucao: 'Completa',
    alcance: 'Curto',
    efeito: '1 criatura conjurada',
    duracao: 'Sustentada',
  },
  consagrar: {
    nome: 'Consagrar',
    execucao: 'Padrão',
    alcance: 'Longo',
    area: 'Esfera com 9m de raio',
    duracao: '1 dia',
  },
  controlarPlantas: {
    nome: 'Controlar Plantas',
    execucao: 'Padrão',
    alcance: 'Curto',
    area: 'quadrado com 9m de lado',
    duracao: 'Cena',
    resistencia: 'Reflexos anula',
  },
  criarElementos: {
    nome: 'Criar Elementos',
    execucao: 'Padrão',
    alcance: 'Curto',
    efeito: 'Elemento escolhido',
    duracao: 'Instantânea',
  },
  criarIlusao: {
    nome: 'Criar Ilusão',
    execucao: 'Padrão',
    alcance: 'Médio',
    efeito: 'Ilusão que se estende a até 4 cubos de 1,5m',
    duracao: 'Cena',
    resistencia: 'Vontade desacredita',
  },
  curarFerimentos: {
    nome: 'Curar Ferimentos',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Instantânea',
  },
  despedacar: {
    nome: 'Despedaçar',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 critura ou objeto mundano pequeno',
    duracao: 'Instantânea',
    resistencia: 'Fortitude parcial ou Reflexos anula',
  },
  detectarAmeacas: {
    nome: 'Detectar Ameaças',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Esfera de 9m de raio',
    duracao: 'Instantânea',
  },
  disfarceIlusorio: {
    nome: 'Disfarce Ilusório',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: 'Cena',
    resistencia: 'Vontade desacredita',
  },
  enfeiticar: {
    nome: 'Enfeitiçar',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 humanoide',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  escudoDaFe: {
    nome: 'Escudo da Fé',
    execucao: 'Reação',
    alcance: 'Curto',
    alvo: '1 criatura',
    duracao: '1 turno',
  },
  escuridao: {
    nome: 'Escuridão',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 objeto',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  explosaoDeChamas: {
    nome: 'Explosão de Chamas',
    execucao: 'Padrão',
    alcance: '6m',
    area: 'Cone',
    duracao: 'Instantânea',
  },
  hipnotismo: {
    nome: 'Hipnotismo',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Criaturas escolhidas de ND 2 ou menor',
    duracao: '1d4 rodadas',
    resistencia: 'Vontade anula',
  },
  imagemEspelhada: {
    nome: 'Imagem Espelhada',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: 'Cena',
  },
  infligirFerimentos: {
    nome: 'Infligir Ferimentos',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Instantânea',
    resistencia: 'Fortitude reduz à metade',
  },
  lequeCromatico: {
    nome: 'Leque Cromático',
    execucao: 'Padrão',
    alcance: '4,5m',
    area: 'Cone',
    duracao: 'Instantânea',
    resistencia: 'Vontade anula',
  },
  luz: {
    nome: 'Luz',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 objeto',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  nevoa: {
    nome: 'Névoa',
    execucao: 'Padrão',
    alcance: 'Curto',
    efeito: 'Nuvem com 6m de raio e altura',
    duracao: 'Cena',
  },
  orientacao: {
    nome: 'Orientação',
    execucao: 'Movimentação',
    alcance: 'Curto',
    alvo: '1 criatura',
    duracao: 'Cena',
  },
  perdicao: {
    nome: 'Perdição',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Criaturas escolhidas',
    duracao: 'Cena',
    resistencia: 'Nenhuma',
  },
  primorAtletico: {
    nome: 'Primor Atlético',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Cena',
  },
  profanar: {
    nome: 'Profanar',
    execucao: 'Padrão',
    alcance: 'Longo',
    area: 'Esfera com 9m de raio',
    duracao: '1 dia',
  },
  protecaoDivina: {
    nome: 'Proteção Divina',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Cena',
  },
  quedaSuave: {
    nome: 'Queda Suave',
    execucao: 'Reação',
    alcance: 'Curto',
    alvo: '1 criatura ou objeto com até 200kg',
    duracao: 'Até chegar ao solo ou cena, o que vier primeiro',
  },
  raioDoEnfraquecimento: {
    nome: 'Raio do Enfraquecimento',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 criatura',
    duracao: 'Cena',
    resistencia: 'Fortitude parcial',
  },
  resistenciaAEnergia: {
    nome: 'Resistência a Energia',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Cena',
  },
  santuario: {
    nome: 'Santuário',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Cena',
    resistencia: 'Vontade anula',
  },
  setaInfalivelDeTalude: {
    nome: 'Seta Infalível de Talude',
    execucao: 'Padrão',
    alcance: 'Médio',
    alvo: 'Até 2 criaturas',
    duracao: 'Instantânea',
  },
  sono: {
    nome: 'Sono',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 criatura de ND 2 ou menor',
    duracao: 'Cena',
    resistencia: 'Vontade parcial',
  },
  suporteAmbiental: {
    nome: 'Suporte Ambiental',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: '1 dia',
  },
  teia: {
    nome: 'Teia',
    execucao: 'Padrão',
    alcance: 'Curto',
    area: 'Cubo com 6m de lado',
    duracao: 'Cena',
    resistencia: 'Reflexos anula',
  },
  toqueChocante: {
    nome: 'Toque Chocante',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 criatura',
    duracao: 'Instantânea',
    resistencia: 'Fortitude reduz à metade',
  },
  trancaArcana: {
    nome: 'Tranca Arcana',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: '1 objeto Grande ou menor',
    duracao: 'Permanente',
  },
  tranquilidade: {
    nome: 'Tranquilidade',
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: '1 animal ou humanoide',
    duracao: 'Cena',
    resistencia: 'Vontade parcial',
  },
  transmutarObjetos: {
    nome: 'Transmutar Objetos',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: 'Matéria-prima, como madeeira, rochas, ossos',
    duracao: 'Cena',
  },
  visaoMistica: {
    nome: 'Visão Mística',
    execucao: 'Padrão',
    alcance: 'Toque',
    alvo: 'Você',
    duracao: 'Cena',
  },
  vitalidadeFantasma: {
    nome: 'Vitalidade Fantasma',
    execucao: 'Padrão',
    alcance: 'Pessoal',
    alvo: 'Você',
    duracao: 'Instantânea',
  },
};
