version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:20.18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-version: v3
      - run:
          name: Run Tests
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
