import Equipment, {
  AppliedEnchantment,
  AppliedModification,
  DamageAttribute,
  DamageType,
  DefenseEquipment,
  ExtraDamage,
  WeaponAction,
  WeaponCategory,
} from '../../../interfaces/Equipment';
import Skill from '../../../interfaces/Skills';
import { DiceRoll } from '../../../interfaces/DiceRoll';
import { ItemE, ItemMod } from '../../../interfaces/Rewards';
import { isDefenseGroup } from './equipmentCatalog';

export type StatField =
  | 'dano'
  | 'atkBonus'
  | 'critico'
  | 'defenseBonus'
  | 'armorPenalty';

/**
 * Shape of the ItemEditorDialog form state. Kept here (not in the dialog) so the
 * pure `buildSavedItem` composition can be unit-tested without React.
 */
export interface ItemEditorFormState {
  customDisplayName: string;
  quantityText: string;
  spacesText: string;
  descricao: string;
  rolls: DiceRoll[];
  danoText: string;
  atkBonusText: string;
  criticoText: string;
  customSkill: Skill | '';
  damageAttribute: DamageAttribute;
  // '' = herda a categoria do catálogo (via getEffectiveWeaponCategory);
  // para itens custom, '' = sem categoria = sempre proficiente.
  weaponCategory: WeaponCategory | '';
  actionDamageAttributes: Record<string, DamageAttribute>;
  defenseBonusText: string;
  armorPenaltyText: string;
  isHeavyArmor: boolean;
  selectedModifications: ItemMod[];
  selectedMaterial: string;
  selectedEnchantments: ItemE[];
  selectedConjuradoraSpell: string;
  userExtraDamage: {
    id: string;
    dice: string;
    damageType: DamageType;
    source: 'user';
  }[];
}

/**
 * Builds the persisted Equipment from the editor form, BEFORE running the
 * enhancement pipeline (`applyItemEnhancements`). Pure — no React, no side
 * effects — so the save composition is directly testable.
 *
 * Stat fields (`dano`/`atkBonus`/`critico` for weapons, `defenseBonus`/
 * `armorPenalty` for armor & shields) are written from the form ONLY when the
 * user manually edited that stat group. When untouched, the fields inherit the
 * item's current values and the enhancement pipeline recomputes them from the
 * `base*` snapshots. Writing the form's (preview) values on an untouched item
 * would let `captureBaseValues` snapshot an already base+delta value as the new
 * base, double-applying the modification (e.g. Reforçada +2/+2 instead of +1/+1).
 */
export function buildSavedItem(
  item: Equipment,
  form: ItemEditorFormState,
  manualEditedFields: Set<StatField>
): Equipment {
  const isWeapon = item.group === 'Arma';
  const isDefense = isDefenseGroup(item.group);

  const quantity = Math.max(1, parseInt(form.quantityText, 10) || 1);
  const spaces =
    form.spacesText === ''
      ? item.spaces
      : parseFloat(form.spacesText.replace(',', '.'));

  const persistedMods: AppliedModification[] = form.selectedModifications.map(
    (m) => ({
      mod: m.mod,
      specialMaterial:
        m.mod === 'Material especial' ? form.selectedMaterial : undefined,
    })
  );

  const persistedEnchantments: AppliedEnchantment[] =
    form.selectedEnchantments.map((e) => ({
      enchantment: e.enchantment,
      selectedSpell:
        e.enchantment === 'Conjuradora' && form.selectedConjuradoraSpell
          ? form.selectedConjuradoraSpell
          : undefined,
    }));

  const persistedUserExtraDamage: ExtraDamage[] = form.userExtraDamage
    .filter((e) => e.dice.trim().length > 0)
    .map((e) => ({
      id: e.id,
      dice: e.dice.trim(),
      damageType: e.damageType,
      source: 'user' as const,
    }));

  const next: Equipment = {
    ...item,
    customDisplayName: form.customDisplayName.trim() || undefined,
    quantity,
    spaces,
    descricao: form.descricao.trim() || undefined,
    rolls: form.rolls.length > 0 ? form.rolls : undefined,
    modifications: persistedMods.length > 0 ? persistedMods : undefined,
    enchantments:
      persistedEnchantments.length > 0 ? persistedEnchantments : undefined,
    // Replace user extra damage; derived entries are regenerated by
    // applyItemEnhancements downstream.
    extraDamage:
      persistedUserExtraDamage.length > 0
        ? persistedUserExtraDamage
        : undefined,
  };

  const weaponStatTouched =
    manualEditedFields.has('dano') ||
    manualEditedFields.has('atkBonus') ||
    manualEditedFields.has('critico');
  const defenseStatTouched =
    manualEditedFields.has('defenseBonus') ||
    manualEditedFields.has('armorPenalty');

  if (isWeapon) {
    if (weaponStatTouched) {
      const atkBonus = parseInt(form.atkBonusText, 10);
      next.dano = form.danoText.trim() || item.dano;
      next.atkBonus = Number.isNaN(atkBonus) ? item.atkBonus : atkBonus;
      next.critico = form.criticoText.trim() || item.critico;
    }
    next.customSkill = (form.customSkill || undefined) as Skill | undefined;
    next.damageAttribute = form.damageAttribute;
    // Campo semântico (como customSkill): gravado sempre, sem marcar
    // hasManualEdits — não congela os bônus automáticos da arma.
    next.weaponCategory =
      form.weaponCategory === '' ? undefined : form.weaponCategory;
    if (item.specialActions && item.specialActions.length > 0) {
      next.specialActions = item.specialActions.map((action) => {
        const overridden = form.actionDamageAttributes[action.id];
        if (!overridden) return action;
        // Strip from the action when it matches the resolved-from-weapon
        // default — keeps the saved object clean.
        return { ...action, damageAttribute: overridden } as WeaponAction;
      });
    }
    next.hasManualEdits = weaponStatTouched ? true : undefined;
  }

  let finalItem: Equipment = next;

  if (isDefense) {
    const defenseNext: DefenseEquipment = {
      ...(next as DefenseEquipment),
      isHeavyArmor: item.group === 'Armadura' ? form.isHeavyArmor : undefined,
    };
    if (defenseStatTouched) {
      const defenseBonus = parseInt(form.defenseBonusText, 10);
      const armorPenalty = parseInt(form.armorPenaltyText, 10);
      defenseNext.defenseBonus = Number.isNaN(defenseBonus)
        ? (item as DefenseEquipment).defenseBonus
        : defenseBonus;
      defenseNext.armorPenalty = Number.isNaN(armorPenalty)
        ? (item as DefenseEquipment).armorPenalty
        : armorPenalty;
    }
    defenseNext.hasManualEdits = defenseStatTouched ? true : undefined;
    finalItem = defenseNext;
  }

  return finalItem;
}
