const nomes: {
  [key: string]: any;
} = {
  Humano: {
    Homem: [
      'Aldor',
      'Aran',
      'Beren',
      'Cyriac',
      'Darik',
      'Dravor',
      'Drystan',
      'Eldred',
      'Ghart',
      'Gryffen',
    ],
    Mulher: [
      'Alysia',
      'Avelin',
      'Catryn',
      'Darna',
      'Elenya',
      'Emeria',
      'Glenda',
      'Gylda',
      'Isolda',
    ],
  },
  Anão: {
    Homem: [
      'Arduramm',
      'Bartarinn',
      'Doragramm',
      'Dastoroc',
      'Hardrumm',
      'Guldaramm',
      'Hortroc',
      'Kradug',
      'Khovarinn',
      'Thardaramm',
    ],
    Mulher: [
      'Atrudda',
      'Burgala',
      'Dorotha',
      'Durdala',
      'Gadrina',
      'Ragardda',
      'Thratilga',
      'Thorkala',
      'Thundrila',
      'Undresia',
    ],
  },
  Dahllan: {
    Homem: [
      'Asterius',
      'Aulus',
      'Caelus',
      'Glabus',
      'Jartus',
      'Kargan',
      'Orgun',
      'Tiberius',
      'Tyraxus',
      'Vobius',
    ],
    Mulher: [
      'Aster',
      'Azalia',
      'Celandine',
      'Dhala',
      'Galya',
      'Lhyria',
      'Lura',
      'Tulipa',
      'Tyka',
      'Violeta',
    ],
  },
  Elfo: {
    Homem: [
      'Avoldar',
      'Ellandor',
      'Felarin',
      'Glorandal',
      'Farandhil',
      'Kirrion',
      'Lurienthel',
      'Myrthallar',
      'Thassarion',
      'Zharian',
    ],
    Mulher: [
      'Allora',
      'Auruel',
      'Calaena',
      'Eloen',
      'Faunalyn',
      'Kethryllia',
      'Laurena',
      'Merethy',
      'Thassalya',
      'Yathanallia',
    ],
  },
  Goblin: {
    Homem: [
      'Ark',
      'Barg',
      'Buduc',
      'Crag',
      'Krig',
      'Rasg',
      'Tabo',
      'Ulerc',
      'Vrix',
      'Vrug',
    ],
    Mulher: [
      'Ashi',
      'Floba',
      'Grin',
      'Iga',
      'Mikhi',
      'Prixa',
      'Pylda',
      'Shug',
      'Sizz',
      'Vruga',
    ],
  },
  Lefou: {
    primeiroNome: [
      'Alma',
      'Eco',
      'Estrela',
      'Fulgor',
      'Furacão',
      'Sol',
      'Tempestade',
      'Tremor',
      'Uivo',
      'Zênite',
    ],
    segundoNome: {
      Homem: [
        'Afiado',
        'Cadavérico',
        'da Perdição',
        'do Ocaso',
        'Eterno',
        'Herege',
        'Imortal',
        'Maldito',
        'Rubro',
        'Serrilhado',
      ],
      Mulher: [
        'Afiada',
        'Cadavérica',
        'da Perdição',
        'do Ocaso',
        'Eterna',
        'Herege',
        'Imortal',
        'Maldita',
        'Rubra',
        'Serrilhada',
      ],
    },
  },
  Minotauro: {
    Homem: [
      'Moufen',
      'Emsia Bravestriker',
      'Faster',
      'Moufen',
      'Emsia',
      'Erana',
      'Iassia',
      'Hirgiran',
      'Tirmaruk',
      'Brangajan',
      'Zamfuran',
      'Djundrin',
    ],
    Mulher: [
      'Winafa',
      'Hilaken',
      'Viafen',
      'Erazara',
      'Oenkane',
      'Muuvin',
      'Seora',
      'Laankane',
      'Raasnas',
      'Aneris',
    ],
  },
  Qareen: {
    Homem: [
      'Ahad',
      'Barakat',
      'Dawud',
      'Hossam',
      'Jaffah',
      'Kirud',
      'Nizur',
      'Sulid',
      'Tariq',
      'Wassim',
    ],
    Mulher: [
      'Aliyah',
      'Batuhla',
      'Hanifa',
      'Jahira',
      'Lalyla',
      'Mhyla',
      'Nirad',
      'Safirah',
      'Sahla',
      'Zakiya',
    ],
  },
  Golem: {
    Homem: ['Golenzin'],
    Mulher: ['Gola'],
  },
  Hynne: {
    Homem: [
      'Frodo',
      'Arno',
      'Flippo',
      'Gleppin',
      'Guido',
      'Haldo',
      'Meric',
      'Pippo',
      'Saruc',
    ],
    Mulher: [
      'Arabella',
      'Ghyla',
      'Joly',
      'Lili',
      'Lobelia',
      'Malva',
      'Prinna',
      'Nyra',
    ],
  },
  Kliren: {
    Homem: ['Kliren'],
    Mulher: ['Klirena'],
  },
  Medusa: {
    Homem: ['Meduso'],
    Mulher: ['Medusa'],
  },
  Osteon: {
    Homem: ['Evass'],
    Mulher: ['Noita'],
  },
  Sereia: {
    Homem: ['Sereio'],
    Mulher: ['Serena'],
  },
  Sílfide: {
    Homem: ['Silfide'],
    Mulher: ['Silfida'],
  },
  Trog: {
    Homem: ['Trogo'],
    Mulher: ['Traga'],
  },
  'Suraggel (Aggelus)': {
    Homem: ['Aggelus'],
    Mulher: ['Aggelas'],
  },
  'Suraggel (Sulfure)': {
    Homem: ['Sulfeto'],
    Mulher: ['Sulfata'],
  },
};

export default nomes;
