const nomes = {
  Humano: {
    Homem: [
      'Aldor',
      'Aran',
      'Beren',
      'Cyriac',
      'Darik',
      'Dravor',
      'Drystan',
      'Eldred',
      'Ghart',
      'Gryffen',
    ],
    Mulher: [
      'Alysia',
      'Avelin',
      'Catryn',
      'Darna',
      'Elenya',
      'Emeria',
      'Glenda',
      'Gylda',
      'Isolda',
    ],
  },
  Anão: {
    Homem: [
      'Arduramm',
      'Bartarinn',
      'Doragramm',
      'Dastoroc',
      'Hardrumm',
      'Guldaramm',
      'Hortroc',
      'Kradug',
      'Khovarinn',
      'Thardaramm',
    ],
    Mulher: [
      'Atrudda',
      'Burgala',
      'Dorotha',
      'Durdala',
      'Gadrina',
      'Ragardda',
      'Thratilga',
      'Thorkala',
      'Thundrila',
      'Undresia',
    ],
  },
  Dahllan: {
    Homem: ['Darlan'],
    Mulher: ['Darlene'],
  },
  Lefou: {
    Homem: ['Lefex'],
    Mulher: ['Lefoa'],
  },
  Elfo: {
    Homem: [
      'Avoldar',
      'Ellandor',
      'Felarin',
      'Glorandal',
      'Farandhil',
      'Kirrion',
      'Lurienthel',
      'Myrthallar',
      'Thassarion',
      'Zharian',
    ],
    Mulher: [
      'Allora',
      'Auruel',
      'Calaena',
      'Eloen',
      'Faunalyn',
      'Kethryllia',
      'Laurena',
      'Merethy',
      'Thassalya',
      'Yathanallia',
    ],
  },
  Goblin: {
    Homem: [
      'Ark',
      'Barg',
      'Buduc',
      'Crag',
      'Krig',
      'Rasg',
      'Tabo',
      'Ulerc',
      'Vrix',
      'Vrug',
    ],
    Mulher: [
      'Ashi',
      'Floba',
      'Grin',
      'Iga',
      'Mikhi',
      'Prixa',
      'Pylda',
      'Shug',
      'Sizz',
      'Vruga',
    ],
  },
  Lefeu: {
    Homem: ['Lefeuso'],
    Mulher: ['Lefona'],
  },
  Minotauro: {
    Homem: ['Minotouro'],
    Mulher: ['Minotaura'],
  },
  Qareen: {
    Homem: ['Eliezer'],
    Mulher: ['Eliana'],
  },
  Golem: {
    Homem: ['Golenzin'],
    Mulher: ['Gola'],
  },
  Hynne: {
    Homem: ['Frodo'],
    Mulher: ['Hynne'],
  },
  Kliren: {
    Homem: ['Kliren'],
    Mulher: ['Klirena'],
  },
  Medusa: {
    Homem: ['Meduso'],
    Mulher: ['Medusa'],
  },
  Osteon: {
    Homem: ['Evass'],
    Mulher: ['Noita'],
  },
  Sereia: {
    Homem: ['Sereio'],
    Mulher: ['Serena'],
  },
  Sílfide: {
    Homem: ['Silfide'],
    Mulher: ['Silfida'],
  },
  Trog: {
    Homem: ['Trogo'],
    Mulher: ['Traga'],
  },
  'Suraggel (Aggelus)': {
    Homem: ['Aggelus'],
    Mulher: ['Aggelas'],
  },
  'Suraggel (Sulfure)': {
    Homem: ['Sulfeto'],
    Mulher: ['Sulfata'],
  },
};

export default nomes;
